### PR TITLE
Consistently quote variables in shell scripts

### LINKED ISSUE #4: Does not support orgs with spaces in name
Eg. "Some organization".
`cf target -o <<parameters.org>> -s <<parameters.space>>`
should probably be changed to 
`cf target -o "<<parameters.org>>" -s <<parameters.space>>`

### PR DESCRIPTION
**Pull request by shakuzen**
This is best practice that prevents things like word splitting, which will allow spaces and blank arguments to be passed.
See https://github.com/koalaman/shellcheck/wiki/SC2086

Fixes #4

### CODE REVIEW

**Comment by shakuzen** [comment]
I also ran into this as an issue because our live site does not use a sub-domain, but setting the `live_subdomain` to a blank string was resulting in an error because the command just ended up like `cf map-route micrometer-docs-dark micrometer.io -n ` with a dangling argument.

**Comment by iynere** [comment]
thanks ! @shakuzen we definitely need to be better about this

**Comment by eddiewebb** [comment]
Seems the issue of live_subdomain merits additional change to only provide -n when that value is set. I am surprised passing an empty string to that give the results folks would want.

**Comment by shakuzen** [comment]
> Seems the issue of live_subdomain merits additional change to only provide -n when that value is set.

That would be better, I agree. I just didn't want to make the change in this pull request.

> I am surprised passing an empty string to that give the results folks would want.

When I tested with one command at least, it seemed to work as desired.

**Pull request merged**
